// wof_repl.cpp
// WOFLANG Project Stub
// This file is part of the autogenerated structure.
// Fill in implementation details here as needed.
#include "repl_reload_support.cpp"

...

if (line == ":reload") {
    handle_repl_reload(interpreter);
    continue;
}
